- name: Advanced NMAP Scan using NSE
  hosts: localhost
  vars:
    ports:
      - 22
      - 443
    scan_host: latebits.com
  tasks:
  - name: Running Nmap NSE scan
    shell: "nmap -Pn -p {{ ports|join(',') }} --script {{ item }} -oA nmap-{{ item }}-results-%Y-%m-%d {{ scan_host }}"
    with_items:
      - ssl-enum-ciphers
      - ssl-cert
      - ssh2-enum-algos
